# Generated by Django 4.2.4 on 2023-08-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_note_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
